on:
  schedule: "0 0 * * *"
  workflow_dispatch:
jobs:
  supersemgrep:
    runs-on: ubuntu-latest
    container: ghcr.io/returntocorp/supersemgrep
    env:
      SEMGREP_RULES: "rules/github.yaml"
      SEMGREP_DEPLOYMENT_ID: "1930"
      SEMGREP_APP_TOKEN: "${{ secrets.SEMGREP_APP_TOKEN }}"
    steps:
      - uses: actions/checkout@v2
      - run: supersemgrep-agent
